#!/usr/bin/env bash

# act
# use nektos/act to simulate github actions on push

set -o errexit
set -o nounset
set -o pipefail
IFS=$'\n\t'
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi
cd "$(dirname "$0")/.."

act push --container-architecture linux/amd64
