#!/usr/bin/env sh

set -e                             # stop on error
[ -n "$DEBUG" ] && set -v

cd `dirname $0`/..                 # work from project root
[ -f config.env ] && . config.env  # supply env vars

clojure -A:test -M -m kaocha.runner "$@"
