# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'flipper'
gem 'flipper-sequel'
gem 'flipper-ui'
gem 'pg'
gem 'rack'
gem 'rack-session'
gem 'sequel'
gem 'webrick'
