name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options:
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      REDIS_URL: redis://127.0.0.1:6379/0
      JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1:5432/postgres?user=postgres&password=postgres
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
          clj-kondo: latest
      - run: clojure -A:test -P  # cache deps
      - uses: actions/cache@v3.2.4
        env:
          cache-name: maven-cache
        with:
          path: ~/.m2
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('deps.edn') }}
      - run: script/test
